import Head from 'next/head'


export default function Home() {

  return (
    <div id="bodyy" className="flex flex-col items-center justify-around min-h-screen py-2">
      <Head>
        <title>slowmates</title>
        <link rel="icon" href="/images/logo_transparent.png" />
        <meta property="og:title" content="slowmates" key="ogtitle" />
        <meta property="og:description" content="Slowmates is a generative NFT collection." key="ogdesc" />
        <meta property="og:type" content="website" key="ogtype" />
        <meta property="og:url" content="https://slowmates.io/" key="ogurl"/>
        <meta property="og:image" content="https://slowmates.io/images/logo_transparent.png" key="ogimage"/>
        <meta property="og:site_name" content="https://slowmates.io/" key="ogsitename" />
        <meta name="twitter:card" content="summary_large_image" key="twcard"/>
        <meta property="twitter:domain" content="https://twitter.com/" key="twdomain" />
        <meta property="twitter:url" content="https://twitter.com/slowmates" key="twurl" />
        <meta name="twitter:title" content="slowmatess" key="twtitle" />
        <meta name="twitter:description" content="Slowmates is a generative NFT collection." key="twdesc" />
        <meta name="twitter:image" content="https://slowmates.io/images/logo.png" key="twimage" />
      </Head>


      <div id="root">
          <div className="flex items-center justify-center w-full border-b-2 border-r-8 border-opacity-0 border-l-8	pb-6 border-opacity-0">
            <a href="/" className=""><img src="images/logo_transparent.png" width="108" alt="" className="logo_transparent-image" /></a>
            <nav className="flex flex-wrap flex-row justify-around PermanentMarker-Regular">
              <a href="/mint" className="text-4xl text-black hover:underline m-6">Mint</a>
              <a href="#about" className="text-4xl text-black hover:underline m-6">About</a>
              <a href="#rarity" className="text-4xl text-black hover:underline m-6">Rarity</a>
              <a href="#team" className="text-4xl text-black hover:underline m-6">Team</a>
              <a href="https://twitter.com/slowmates" className="text-4xl  hover:text-black m-6 text-blau">TWITTER</a>
              <a href="https://discord.gg/N239QjZFE2" className="text-4xl  hover:text-black m-6 text-blau">DISCORD</a>
            </nav>

          </div>

      

          <div className="flex flex-col items-center border-b-20 ">
            <img src="images/slowmate_creation_timelapse.gif"/>
            <a href="/mint" className="mt-4 PermanentMarker-Regular text-4xl border-6 bg-white rounded-xl ring-4 text-black hover:text-black p-2 ">MINT</a>
          </div>



            <div className="flex flex-col items-center">


          <div className="mt-6 border-b-2 py-6 border-l-8	pb-6 border-opacity-0">
            <div id="about" className="flex flex-wrap lg:flex-nowrap justify-around items-center">
                  <div className="lg:w-1/2 w-3/4">
                    <h1 className="text-4xl PermanentMarker-Regular text-black font-bold">What are Slowmates? </h1>
                    <p className="text-2xl PermanentMarker-Regular text-black ">
                      "Slowmates are 7,777 unique sloth NFTs coming soon to the Ethereum blockchain. Each Slowmate is generated by combining 5 random sloth traits of different rarities: fur, eyes, mouth, head, and body.  The random combination are endless so there is enough variety for everyone.  Mint your NFT so that you can find your Slowmate."
                    </p>
                  </div>
                  <img className="lg:w-1/2 w-3/4" src="images/collage.png" width="500px" />
            </div>

            </div>

              <div id="rarity" className="flex flex-col items-center border-b-20 ">
                <img src="images/rarity.png"/>
              </div>

              <div id="team" className="flex flex-col items-center border-b-20 ">
                <img src="images/team.png"/>
              </div>
              
          </div>
          </div>
    </div>
    )
  }
