import Head from 'next/head'

export default function Terms() {

  return (
    <div id="bodyy" className="flex flex-col items-center justify-center min-h-screen py-2">
      <Head>
      <link rel="icon" href="/images/favicon.png" />
        <meta property="og:title" content="Slowmates" key="ogtitle" />
        <meta property="og:description" content="Slowmates is a generative NFT collection." key="ogdesc" />
        <meta property="og:type" content="website" key="ogtype" />
        <meta property="og:url" content="https://slowmates.io/" key="ogurl"/>
        <meta property="og:image" content="https://slowmates.io/images/logo.png" key="ogimage"/>
        <meta property="og:site_name" content="https://slowmates.io/" key="ogsitename" />
        <meta name="twitter:card" content="summary_large_image" key="twcard"/>
        <meta property="twitter:domain" content="https://slowmates.io/" key="twdomain" />
        <meta property="twitter:url" content="https://slowmates.io/" key="twurl" />
        <meta name="twitter:title" content="Slowmates" key="twtitle" />
        <meta name="twitter:description" content="Slowmates is a generative NFT collection." key="twdesc" />
        <meta name="twitter:image" content="https://slowmates.io/images/logo.png" key="twimage" />
      </Head>


      <div >
          <div className="flex items-center justify-between w-full border-b-2	pb-6">
            <a href="/" className=""><img src="images/logo.png" width="108" alt="" className="logo-image" /></a>
            <nav className="flex flex-wrap flex-row justify-around PermanentMarker-Regular">

              <a href="https://twitter.com/slowmates" className="text-4xl  hover:text-white m-6 text-blau">TWITTER</a>
              <a href="https://discord.gg/N239QjZFE2" className="text-4xl  hover:text-white m-6 text-blau">DISCORD</a>
            </nav>

          </div>

        </div>

        <div className="md:w-2/3 w-4/5 " id="home">




              <div id="roadmap" className="">
                  <br/>
                  <br/>
                  <br/>
                  <br/>
              <h2 className="text-6xl text-center PermanentMarker-Regular text-blau my-4">TERMS & CONDITIONS</h2>
              <ul className="">
                <li className="text-2xl text-white my-6  PermanentMarker-Regular">The Slowmates's are a collection of digital artworks (NFTs) running on the Ethereum network. This website is only an interface allowing participants to exchange digital collectibles. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as the Slowmates smart contract runs on the Ethereum network, there is no ability to undo, reverse, or restore any transactions.</li>

                <li className="text-2xl text-white my-6  PermanentMarker-Regular">This website and its connected services are provided “as is” and “as available” without warranty of any kind. By using this website you are accepting sole responsibility for any an all transactions involving Slowmates. </li>
                <br/>
                <br/>
              <h3 className="text-6xl text-left PermanentMarker-Regular text-purp my-4">OWNERSHIP </h3>

                <li className="text-2xl text-white my-6  PermanentMarker-Regular"> i. You Own the NFT. Each Slowmates is an NFT on the Ethereum blockchain. When you purchase an NFT, you own the underlying Slowmates, the Art, completely. Ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network: at no point may we seize, freeze, or otherwise modify the ownership of any Slowmates.</li>

                <li className="text-2xl text-white my-6  PermanentMarker-Regular"> ii. Personal Use. Subject to your continued compliance with these Terms, Slowmates grants you a worldwide, royalty-free license to use, copy, and display the purchased Art, along with any extensions that you choose to create or use, solely forthe following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace that permits the purchase and sale of your Slowmates / NFT, provided that the marketplace cryptographically verifies each Slowmates owner’s rights to display the Art for their Slowmates to ensure that only the actual owner can display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement, or participation of your Slowmates, provided that the website/application cryptographically verifies each Slowmates owner’s rights to display the Art for their Slowmates to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner ofthe Slowmates leaves the website/application.</li>

                <li className="text-2xl text-white my-6  PermanentMarker-Regular"> iii. Commercial Use. Subject to your continued compliance with these Terms, Slowmates grants you an unlimited, worldwide license to use, copy, and display the purchased Art for the purpose of creating derivative works based upon the Art (“Commercial Use”). Examples of such Commercial Use would e.g. be the use of the Art to produce and sell merchandise products (T-Shirts etc.) displaying copies of the Art. For the sake of clarity, nothing in this Section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of Slowmatess generally, provided that the marketplace cryptographically verifies eachSlowmates owner’s rights to display the Art for their Slowmates to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of Slowmatess generally, provided that the third party website or application cryptographically verifies each Slowmates owner’s rights to display the Art for their Slowmates to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Purchased Slowmates leaves the website/application; or (iii) earning revenue from any of the foregoing.</li>


              </ul>



              </div>
          </div>
    </div>
    )
  }
